name: Build

on:
  push:
    branches: [main]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
  pull_request:

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dioxus-cli
        uses: taiki-e/install-action@main
        with:
          tool: dioxus-cli
      - uses: Swatinem/rust-cache@v2
      - run: dx bundle --release
      - if: github.ref_protected || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: beam-cert-ui-binary
          path: target/dx/release/beam-cert-ui/web/server
  dockerize:
    if: github.ref_protected || github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
    needs: bundle
    name: Build and push Docker image
    uses: samply/github-workflows/.github/workflows/docker-ci.yml@main
    with:
        image-name: "samply/beam-cert-ui"
        push-to: 'dockerhub'
        build-platforms: "linux/amd64"
        artifact-name: "beam-cert-ui-binary"
    secrets:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}